### ISSUE TITLE
Hide pages behind SSO

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/whitebophir_ynh#5]
Hi,
I just found this package and I'm very happy I did. However I had a question: is it possible to lock the random and anonymous whiteboards behind the SSO? My goal would be that ideally, only my users can create whiteboards but anyone can access the created whiteboard. I have to say my knowledge of yunohost's SSO is not that good but I guess the point would be to "blacklist" the following URLs:
- /
- /boards/anonymous
- /boards/random

Any idea how to achieve this?

**Comment by oiseauroch** [comment]
Hi, 
You can blacklist specific pages either with nginx to totally disabling the page or with sso to set it behind authentication.
 
However, there is no authentication mechanism in wbo (see https://github.com/lovasoa/whitebophir/issues/108) so that we can't really achieve what you want automatically.

**Comment by ghost** [comment]
I see, I'll watch out for this feature in whitebophir then!

Thank you very much for your help!
